# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e5e5d27dc22e4882ddacd3a5cf120816aa7362e43d146cf4550de0d7c7f573815c69d332ad6abad34ad66dda20b8c5bab2cdc6c9fa04b3a8b071060f2643c1db

test:
  secret_key_base: 7e826e09a89ffd0d8995f6df2998ff2c63bef559d2b383242f536cd437c11654e32876ebde1c272445ef89ba84b274ae7e08cee51ea72d200dcbca7c6b0f6583

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
